# Generated by Django 2.2.5 on 2019-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0039_messages_templates_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicassistant',
            name='inscription',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('IN_PROGRESS', 'In progress')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='assistantmandate',
            name='appeal',
            field=models.CharField(choices=[('NONE', 'None'), ('POSITIVE_APPEAL', 'Positive appeal'), ('NEGATIVE_APPEAL', 'Negative appeal'), ('APPEAL_IN_PROGRESS', 'Appeal in progress'), ('NO_APPEAL', 'No appeal')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistantmandate',
            name='assistant_type',
            field=models.CharField(choices=[('ASSISTANT', 'Assistant'), ('TEACHING_ASSISTANT', 'Teaching assistant')], default='ASSISTANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistantmandate',
            name='renewal_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SPECIAL', 'Special'), ('EXCEPTIONAL', 'Exceptional')], default='NORMAL', max_length=12),
        ),
        migrations.AlterField(
            model_name='assistantmandate',
            name='state',
            field=models.CharField(choices=[('DECLINED', 'Refused by the assistant'), ('TO_DO', 'Start'), ('TRTS', 'Assistant'), ('PHD_SUPERVISOR', 'Thesis promoter'), ('RESEARCH', 'President of Institute'), ('SUPERVISION', 'Dean of Faculty'), ('VICE_RECTOR', 'Vice-rector of sector'), ('DONE', 'Completed')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('TO_ALL_ASSISTANTS', 'To the assistants'), ('TO_ALL_DEANS', 'To the Deans of Faculty'), ('TO_PHD_SUPERVISOR', 'To Ph.D. promoter'), ('TO_ONE_DEAN', 'To one Dean'), ('TO_ALL_REVIEWERS', 'To all reviewers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='advice',
            field=models.CharField(choices=[('FAVORABLE', 'Favourable'), ('CONDITIONAL', 'Conditional'), ('UNFAVOURABLE', 'Unfavourable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('DONE', 'Completed')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'Thesis promoter'), ('SUPERVISION', 'Dean of Faculty'), ('SUPERVISION_ASSISTANT', 'Dean of Faculty representative'), ('SUPERVISION_DAF', 'DAF'), ('SUPERVISION_DAF_ASSISTANT', 'DAF representative'), ('RESEARCH', 'President of Institute'), ('RESEARCH_ASSISTANT', 'Representative of the Institute President'), ('VICE_RECTOR', 'Vice-rector of sector'), ('VICE_RECTOR_ASSISTANT', 'DAS/CAS'), ('VICE_RECTOR_ASSISTANT_ASSISTANT', 'DAS/CAS representative')], max_length=30),
        ),
    ]
