# Generated by Django 2.2.5 on 2019-12-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0040_auto_20191220_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'Thesis promoter'), ('SUPERVISION', 'Dean of Faculty'), ('SUPERVISION_ASSISTANT', 'Dean of Faculty representative'), ('SUPERVISION_DAF', 'DAF'), ('SUPERVISION_DAF_ASSISTANT', 'DAF representative'), ('RESEARCH', 'President of Institute'), ('RESEARCH_ASSISTANT', 'Representative of the Institute President'), ('VICE_RECTOR', 'Vice-rector of sector'), ('VICE_RECTOR_ASSISTANT', 'DAS/CAS'), ('VICE_RECTOR_ASSISTANT_ASSISTANT', 'DAS/CAS representative')], max_length=40),
        ),
    ]
