# Generated by Django 2.2.10 on 2020-10-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assistant', '0041_auto_20191220_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicassistant',
            name='succeed_confirmation_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
