# Generated by Django 2.2.13 on 2021-04-19 10:54

from django.db import migrations


def remove_unused_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="assistant_administrators").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0042_academicassistant_succeed_confirmation_test_date'),
    ]

    operations = [
        migrations.RunPython(remove_unused_groups, migrations.RunPython.noop, elidable=True)
    ]
