# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations

HTML_FR_BE = "{% autoescape off %}\r\n" \
             "<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n" \
             "<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y " \
             "r\u00e9pondre.</p>\r\n" \
             "<p>La procédure de renouvellement des mandats des assistant·e·s dont le contrat arrive à échéance " \
             "entre le {{ start_date }} et le {{ end_date }} vient de débuter. " \
             "Celle-ci s’effectue intégralement par voie électronique.</p>\r\n" \
             "<p>En ce qui vous concerne, vous êtes dans le cas d’une demande de <b>renouvellement spécial</b> : " \
             "vous êtes proche du nombre maximum d’années de mandat autorisées sans pour autant avoir dépassé " \
             "ce nombre. Si vous le souhaitez, vous pouvez donc introduire une demande de renouvellement spécial " \
             "pour une durée de 1 an, et ce sans donner de justification particulière.</p>\r\n" \
             "<p>Pour accéder à la procédure, il vous suffit de vous rendre sur le portail à la page suivante :" \
             " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
             "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
             "<p>Cordialement,</br>\r\n" \
             "Administration des Ressources Humaines</br>\r\n" \
             "Contact: Marie-Dominique Heureux\r\n" \
             "{% endautoescape %}"

TXT_FR_BE = "<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n" \
            "<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y " \
            "r\u00e9pondre.</p>\r\n" \
            "<p>La procédure de renouvellement des mandats des assistant·e·s dont le contrat arrive à échéance " \
            "entre le {{ start_date }} et le {{ end_date }} vient de débuter. " \
            "Celle-ci s’effectue intégralement par voie électronique.</p>\r\n" \
            "<p>En ce qui vous concerne, vous êtes dans le cas d’une demande de renouvellement spécial : " \
            "vous êtes proche du nombre maximum d’années de mandat autorisées sans pour autant avoir dépassé " \
            "ce nombre. Si vous le souhaitez, vous pouvez donc introduire une demande de renouvellement spécial " \
            "pour une durée de 1 an, et ce sans donner de justification particulière.</p>\r\n" \
            "<p>Pour accéder à la procédure, il vous suffit de vous rendre sur le portail à la page suivante :" \
            " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
            "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
            "<p>Cordialement,</br>\r\n" \
            "Administration des Ressources Humaines</br>\r\n" \
            "Contact: Marie-Dominique Heureux\r\n"

HTML_EN = "{% autoescape off %}\r\n" \
          "<p>Hello {{ first_name }} {{ last_name }},</p>\r\n" \
          "<pThis is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n" \
          "<p>The procedure for renewing the mandates of assistants whose contract expires between " \
          "the {{ start_date }} and the {{ end_date }} has just begun. " \
          "It is conducted by electronic means only.</p>\r\n" \
          "<p>In your case, you are in a <b>special renewal procedure</b> : " \
          "you have almost reached the maximum number of years authorized for a mandate but have yet to surpass it. " \
          "If you so desire, you can apply for a a renewal period of one year, and this, without having " \
          "to give a particular justification.</p>\r\n" \
          "<p>In order to gain access to the procedure, simply click on the following link:" \
          " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
          "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
          "<p>Regards,</br>\r\n" \
          "Human Resources Administration</br>\r\n" \
          "Contact: Marie-Dominique Heureux\r\n" \
          "{% endautoescape %}"

TXT_EN = "<p>Hello {{ first_name }} {{ last_name }},</p>\r\n" \
         "<pThis is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n" \
         "<p>The procedure for renewing the mandates of assistants whose contract expires between " \
         "the {{ start_date }} and the {{ end_date }} has just begun. " \
         "It is conducted by electronic means only.</p>\r\n" \
         "<p>In your case, you are in a special renewal procedure: " \
         "you have almost reached the maximum number of years authorized for a mandate but have yet to surpass it. " \
         "If you so desire, you can apply for a a renewal period of one year, and this, without having " \
         "to give a particular justification.</p>\r\n" \
         "<p>In order to gain access to the procedure, simply click on the following link:" \
         " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
         "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
         "<p>Regards,</br>\r\n" \
         "Human Resources Administration</br>\r\n" \
         "Contact: Marie-Dominique Heureux\r\n"


def update_messages(apps, schema_editor):
    MessageTemplate = apps.get_model("osis_common", "MessageTemplate")

    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_html',
        language='fr-be',
        format="HTML",
        subject="Renouvellement des mandats des assistant·e·s",
        defaults={
            "template": HTML_FR_BE,
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_txt',
        language='fr-be',
        subject="Renouvellement des mandats des assistant·e·s",
        format="PLAIN",
        defaults={
            "template": TXT_FR_BE,
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_html',
        language='en',
        subject="Assistants mandates renewal",
        format="HTML",
        defaults={
            "template": HTML_EN,
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_txt',
        language='en',
        subject="Assistants mandates renewal",
        format="PLAIN",
        defaults={
            "template": TXT_EN,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0043_auto_20210419_1054'),
    ]

    operations = [
        migrations.RunPython(
            update_messages
        ),
    ]
