# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations

HTML_FR_BE = "{% autoescape off %}\r\n" \
             "<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n" \
             "<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y " \
             "r\u00e9pondre.</p>\r\n" \
             "<p>La procédure de renouvellement des mandats des assistant·e·s dont le contrat arrive à échéance " \
             "entre le {{ start_date }} et le {{ end_date }} vient de débuter. " \
             "Celle-ci s’effectue intégralement par voie électronique.</p>\r\n" \
             "<p>Dans votre cas, vous avez atteint le nombre maximum d'années de mandat autorisées pour demander " \
             "un renouvellement normal, donc si vous le souhaitez et si vous avez des circonstances exceptionnelles " \
             "qui le justifient, vous pouvez introduire une demande de renouvellement exceptionnel d'un an. " \
             "Pour cela, nous vous demandons d'apporter une argumentation approfondie pour faciliter la décision " \
             "des autorités sur le caractère exceptionnel ou non de ces circonstances.</p>\r\n" \
             "<p>Pour accéder à la procédure, il vous suffit de vous rendre sur le portail à la page suivante :" \
             " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
             "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
             "<p>Cordialement,</br>\r\n" \
             "Administration des Ressources Humaines</br>\r\n" \
             "Contact: Marie-Dominique Heureux\r\n" \
             "{% endautoescape %}"

TXT_FR_BE = "<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n" \
            "<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y " \
            "r\u00e9pondre.</p>\r\n" \
            "<p>La procédure de renouvellement des mandats des assistant·e·s dont le contrat arrive à échéance " \
            "entre le {{ start_date }} et le {{ end_date }} vient de débuter. " \
            "Celle-ci s’effectue intégralement par voie électronique.</p>\r\n" \
            "<p>Dans votre cas, vous avez atteint le nombre maximum d'années de mandat autorisées pour demander " \
            "un renouvellement normal, donc si vous le souhaitez et si vous avez des circonstances exceptionnelles " \
            "qui le justifient, vous pouvez introduire une demande de renouvellement exceptionnel d'un an. " \
            "Pour cela, nous vous demandons d'apporter une argumentation approfondie pour faciliter la décision " \
            "des autorités sur le caractère exceptionnel ou non de ces circonstances.</p>\r\n" \
            "<p>Pour accéder à la procédure, il vous suffit de vous rendre sur le portail à la page suivante :" \
            " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
            "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
            "<p>Cordialement,</br>\r\n" \
            "Administration des Ressources Humaines</br>\r\n" \
            "Contact: Marie-Dominique Heureux\r\n"

HTML_EN = "{% autoescape off %}\r\n" \
          "<p>Hello {{ first_name }} {{ last_name }},</p>\r\n" \
          "<pThis is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n" \
          "<p>The procedure for renewing the mandates of assistants whose contract expires between " \
          "the {{ start_date }} and the {{ end_date }} has just begun. " \
          "It is conducted by electronic means only.</p>\r\n" \
          "<p>In your case, you have reached the maximum number of years allowed to apply for a normal renewal. " \
          "You may however, if you so desire and if it can be justified by exceptional circumstances, " \
          "apply for a one-off renewal period of one year. Therefore, we ask you to provide detailed arguments " \
          "in order to facilitate the decision of the authorities on the exceptional nature or not of " \
          "these circumstances.</p>\r\n" \
          "<p>In order to gain access to the procedure, simply click on the following link:" \
          " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
          "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
          "<p>Regards,</br>\r\n" \
          "Human Resources Administration</br>\r\n" \
          "Contact: Marie-Dominique Heureux\r\n" \
          "{% endautoescape %}"

TXT_EN = "<p>Hello {{ first_name }} {{ last_name }},</p>\r\n" \
         "<pThis is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n" \
         "<p>The procedure for renewing the mandates of assistants whose contract expires between " \
         "the {{ start_date }} and the {{ end_date }} has just begun. " \
         "It is conducted by electronic means only.</p>\r\n" \
         "<p>In your case, you have reached the maximum number of years allowed to apply for a normal renewal. " \
         "You may however, if you so desire and if it can be justified by exceptional circumstances, " \
         "apply for a one-off renewal period of one year. Therefore, we ask you to provide detailed arguments " \
         "in order to facilitate the decision of the authorities on the exceptional nature or not of " \
         "these circumstances.</p>\r\n" \
         "<p>In order to gain access to the procedure, simply click on the following link:" \
         " <a href='http://www.uclouvain.be/renouvellement-assistant'>" \
         "http://www.uclouvain.be/renouvellement-assistant</a></p>\r\n" \
         "<p>Regards,</br>\r\n" \
         "Human Resources Administration</br>\r\n" \
         "Contact: Marie-Dominique Heureux\r\n"


def update_messages(apps, schema_editor):
    MessageTemplate = apps.get_model("osis_common", "MessageTemplate")

    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_html',
        language='fr-be',
        format="HTML",
        defaults={
            "reference": 'assistant_assistants_startup_special_renewal_html',
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_txt',
        language='fr-be',
        format="PLAIN",
        defaults={
            "reference": 'assistant_assistants_startup_special_renewal_txt',
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_html',
        language='en',
        format="HTML",
        defaults={
            "reference": 'assistant_assistants_startup_special_renewal_html',
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_txt',
        language='en',
        format="PLAIN",
        defaults={
            "reference": 'assistant_assistants_startup_special_renewal_txt',
            "template": TXT_EN,
        }
    )

    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_html',
        language='fr-be',
        format="HTML",
        subject="Renouvellement des mandats des assistant·e·s",
        defaults={
            "template": HTML_FR_BE,
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_txt',
        language='fr-be',
        subject="Renouvellement des mandats des assistant·e·s",
        format="PLAIN",
        defaults={
            "template": TXT_FR_BE,
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_html',
        language='en',
        subject="Assistants mandates renewal",
        format="HTML",
        defaults={
            "template": HTML_EN,
        }
    )
    MessageTemplate.objects.update_or_create(
        reference='assistant_assistants_startup_except_renewal_txt',
        language='en',
        subject="Assistants mandates renewal",
        format="PLAIN",
        defaults={
            "template": TXT_EN,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0044_update_special_renewal_message_template'),
    ]

    operations = [
        migrations.RunPython(
            update_messages
        ),
    ]
